In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
'max_features': ['sqrt', 'log2', None],
'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)

# fitting the model for grid search
grid.fit(X_train, y_train)

# Print best parameters after tuning
print("Best parameters:", grid.best_params_)

# Predictions
grid_predictions = grid.predict(X_test)

# Print R2 score
from sklearn.metrics import r2_score
r_score = r2_score(y_test, grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_), r_score)

# Results table
import pandas as pd
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best parameters: {'criterion': 'absolute_error', 'max_features': None, 'splitter': 'random'}
The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': None, 'splitter': 'random'}: 0.7121852487133584

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003401,0.000854,0.000799,0.000399,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.528675,0.483088,0.576948,0.640010,0.520308,0.549806,0.054114,18
1,0.002700,0.000680,0.000803,0.000401,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.597059,0.592899,0.488529,0.342634,0.582091,0.520642,0.097524,20
2,0.002406,0.000374,0.000998,0.000001,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.669222,0.613392,0.662917,0.606191,0.537988,0.617942,0.047337,10
3,0.002302,0.000409,0.000997,0.000002,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.621732,0.534177,0.598168,0.547846,0.604989,0.581383,0.034118,13
4,0.003398,0.000585,0.000802,0.000401,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.680419,0.505341,0.784088,0.623219,0.662781,0.651170,0.090227,2
5,0.002798,0.000809,0.000901,0.000197,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.589359,0.561039,0.664011,0.365647,0.617549,0.559521,0.102728,17
6,0.002393,0.000489,0.000501,0.000635,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.481895,0.510997,0.674402,0.555039,0.633356,0.571138,0.072629,15
7,0.002009,0.000321,0.000801,0.000401,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.700006,0.553451,0.617162,0.527667,0.427573,0.565172,0.090951,16
8,0.002299,0.000508,0.001000,0.000002,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.530394,0.619622,0.698851,0.130168,0.593514,0.514510,0.199621,21
9,0.001698,0.000398,0.000599,0.000489,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.305150,0.308430,0.510688,0.614661,0.517821,0.451350,0.123621,24
10,0.003021,0.000552,0.000399,0.000489,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.704093,0.507566,0.758730,0.593588,0.651708,0.643137,0.087161,4
11,0.002306,0.000619,0.000598,0.000488,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.698476,0.609863,0.680013,0.509614,0.602892,0.620172,0.066844,8
12,0.010992,0.001406,0.000599,0.000489,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.510515,0.424287,0.572435,0.701206,0.686472,0.578983,0.105028,14
13,0.008402,0.000863,0.000607,0.000496,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.590855,0.535696,0.735122,0.638701,0.629483,0.625971,0.065530,7
14,0.010818,0.001437,0.000799,0.000399,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.029925,0.463365,0.630843,0.623370,0.577730,0.465047,0.225648,23
15,0.009207,0.000883,0.000598,0.000489,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.720992,0.558514,0.705624,0.636035,0.594690,0.643171,0.062489,3
16,0.016296,0.002906,0.000599,0.000489,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.639902,0.542398,0.708029,0.619352,0.627628,0.627462,0.052816,6
17,0.013401,0.002662,0.000600,0.000490,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.703066,0.674954,0.716546,0.567411,0.647802,0.661956,0.052874,1
18,0.003095,0.000487,0.000000,0.000000,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.652645,0.560064,0.643068,0.536087,0.600152,0.598403,0.045373,11
19,0.002300,0.000610,0.000599,0.000489,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.443470,0.494592,0.668380,0.512650,0.531360,0.530090,0.075091,19
20,0.003502,0.001054,0.000199,0.000399,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.459444,0.490705,0.650032,0.699018,0.623498,0.584539,0.093130,12
21,0.002606,0.000591,0.000199,0.000399,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.535043,0.494406,0.546875,0.396337,0.574046,0.509341,0.062047,22
22,0.003990,0.000633,0.000500,0.000446,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.714276,0.430882,0.723341,0.606108,0.615492,0.618020,0.105382,9
23,0.002398,0.000374,0.000400,0.000490,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.673030,0.503712,0.734749,0.657829,0.630211,0.639906,0.076232,5

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 33
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [13]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
preinput

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.18217616,  0.37742013,  0.75672907, -0.98885138,  2.00280702]])

In [14]:
Future_Prediction=grid.predict(preinput)

#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[34439.8559]